# Description: Dockerfile for Discord bot

# Use an official Python runtime as a parent image
FROM python:3.11.4

# Set the working directory in the container to /app
WORKDIR /code

# Copy the current directory contents into the container at /app
COPY . .


# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt


#CMD ["python", "-u", "src/main.py"]
CMD ["/usr/local/bin/python", "-m", "src"]